name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.2.8
  AWS_REGION: ap-northeast-1

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION}}
      - name: Terrafrom format
        run: |
          terraform fmt -check
      - name: Show GitHub context
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Workflow: $GITHUB_WORKFLOW"
      - name: Show AWS role ARN
        run: |
          echo "${AWS_IAM_ROLE_ARN}" | sed 's#arn:aws:iam::[0-9]*:role/#arn:aws:iam::************:role/#'
        env:
          AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION}}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN}}
      - name: Terrafrom init
        run: |
          terraform init -no-color
      - name: Terraform validate
        run: |
          terraform validate -no-color
