name: "z Slack Notify"

on:
  workflow_dispatch:

jobs:
  Notify:
    name: slack Notify
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notify
        uses: slackapi/slack-github-action@v4.0.0
        with:
          method: chat.postMessage
          token: ${{secrets.SLACK_BOT_TOKEN}}
          payload: |
            channel: "C0BPHBBCAPQ"
            text: "コミットされたよ"
